version: "3"
services:
  kudzu:
    build:
      context: .
      args:
        KUDZU_DEBUG: "${KUDZU_DEBUG}"
    ports:
      - '8080:8080'
      - '2345:2345'
    volumes:
      - ./kudzu:/kudzu
      - ./kudzu-cli:/kudzu-cli
    image: kudzu-dev
    env_file:
      - .env
